/*
 * go_flutter_exam User
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Age int64 `json:"age"`
}
